### ISSUE TITLE
Please activate your account before trying to login.

### ISSUE THREAD

**Issue by yuri25** [bpocallaghan/titan#13]
There are no users in the database .... Including no admin. How to create an administrator and get into the admin panel? Thank.

**Comment by bpocallaghan** [comment]
Hi @yuri25 
Sorry, for some reasons I did not receive a mail - or just missed it.
Once you ran the command `php artisan titan:setup` it will copy the `UsersTableSeeder.php` for you. You can then open it and update/add the admin credentials you want. Then you can run command `php artisan db:seed` to create the user for you.
Please let me know if it did not work for you

**Comment by yuri25** [comment]
Hi @bpocallaghan 

# php artisan db:seed

   `Illuminate\Contracts\Container\BindingResolutionException  : Target class [RoleTableSeeder] does not exist.
`

>   at /...../vendor/laravel/framework/src/Illuminate/Container/Container.php:806
>     802|
>     803|         try {
>     804|             $reflector = new ReflectionClass($concrete);
>     805|         } catch (ReflectionException $e) {
>   > 806|             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
>     807|         }
>     808|
>     809|         // If the type is not instantiable, the developer is attempting to resolve
>     810|         // an abstract type such as an Interface or Abstract Class and there is
> 
>   Exception trace:
> 
>   1   ReflectionException::("Class RoleTableSeeder does not exist")
>       /......./vendor/laravel/framework/src/Illuminate/Container/Container.php:804
> 
>  2   ReflectionClass::__construct("RoleTableSeeder")
>       /......../vendor/laravel/framework/src/Illuminate/Container/Container.php:804
> 
>   Please use the argument -v to see more details.
>

**Comment by yuri25** [comment]
> # php artisan titan:db:seed
> 
> Seeding: RoleTableSeeder
> Seeding: BannerTableSeeder
> Seeding: PageTableSeeder
> Seeding: NavigationAdminTableSeeder
> Database seeding completed successfully.

Where is the seeding in the user table?

**Comment by bpocallaghan** [comment]
Hi @yuri25 
Okys, I noticed that there was a slight mixup with the install command.
I've added a new version - you can update to latest version or you can do the following.

`composer dump-autoload`
Open the file `database/seeds/DatabaseSeeder.php` and uncomment the line 14.
`php artisan db:seed`

What happened:
There are 'titan' seeders (roles, banners, pages, navigation) and then the 'app' seeder (users) is inside your project. The titan seeders worked but the users one did not (it was commented out).
The reason that Users is inside your project and not titan, is that you can easily edited it and not have a 'dummy' user inside your table.

Please let me know if I can help and sorry about the hassle.

**Comment by yuri25** [comment]
Thank you so much! It works now!

**Comment by bpocallaghan** [comment]
@yuri25 
Awesome, please shout if you have any questions / issues.
Happy Coding :)
