### ISSUE TITLE
Error on your site, please see.

### ISSUE THREAD

**Issue by yuri25** [bpocallaghan/titan#19]
http://bpocallaghan.co.za/blog

> Facade\Ignition\Exceptions\ViewException
> Trying to get property 'thumbUrl' of non-object (View: /home/forge/bpocallaghan.co.za/resources/views/website/blog/pagination.blade.php)

**Comment by bpocallaghan** [comment]
Hi @yuri25 
Thanks for notifying me. It tried to view articles without photos. Its fixed. Thanks again!
