### ISSUE TITLE
 php artisan titan:install   - error

### ISSUE THREAD

**Issue by yuri25** [bpocallaghan/titan#20]
> # php artisan titan:install
> Busy running "composer dump-autoload" to index the files. Please wait a few seconds.
> The following will update your .env file.
> 
>  What is your APP_NAME?:
>  > titan
> 
>  What is your APP_DESCRIPTION?:
>  > huita
> 
>  What is your APP_KEYWORDS?:
>  > test
> 
>  What is your APP_AUTHOR?:
>  > admin
> 
>  What is your APP_URL?:
>  > ptzauto.ru
> .env was updated. (Extra environment variables were addted at the top)
> Migration table created successfully.

........................................................................................................................................................

> Seeding: RoleTableSeeder
> Seeding: BannerTableSeeder
> Seeding: PageTableSeeder
> Seeding: NavigationAdminTableSeeder
> Database seeding completed successfully.

   Illuminate\Contracts\Container\BindingResolutionException  : Target class [UsersTableSeeder] does not exist.

  

> at /........../ptzauto.ru/vendor/laravel/framework/src/Illuminate/Container/Container.php:806
>     802|
>     803|         try {
>     804|             $reflector = new ReflectionClass($concrete);
>     805|         } catch (ReflectionException $e) {
>   > 806|             throw new BindingResolutionException("Target class [$concrete] does not exist.", 0, $e);
>     807|         }
>     808|
>     809|         // If the type is not instantiable, the developer is attempting to resolve
>     810|         // an abstract type such as an Interface or Abstract Class and there is
> 
>   Exception trace:
> 
>   1   ReflectionException::("Class UsersTableSeeder does not exist")
>       /........./ptzauto.ru/vendor/laravel/framework/src/Illuminate/Container/Container.php:804
> 
>   2   ReflectionClass::__construct("UsersTableSeeder")
>       /............/ptzauto.ru/vendor/laravel/framework/src/Illuminate/Container/Container.php:804

  Please use the argument -v to see more details.

**Comment by bpocallaghan** [comment]
Hi @yuri25 
Wowi, sorry, you having lots of trouble with this :)
Do you have that file under `database/seeds`? Weird that it is not finding it?
