### ISSUE TITLE
Images are not uploaded to the gallery

### ISSUE THREAD

**Issue by yuri25** [bpocallaghan/titan#21]
![image](https://user-images.githubusercontent.com/253228/66310874-e5c52b80-e915-11e9-855b-ef3ffa9fcc96.png)

**Comment by yuri25** [comment]
![image](https://user-images.githubusercontent.com/253228/66311008-24f37c80-e916-11e9-8fa8-00ac51827f30.png)

No images:(

**Comment by bpocallaghan** [comment]
Hi @yuri25 
If you press f12 - you will be able to see what the ajax error is.
However I think it might be because you are missing the two upload folders.
Do you have the `public/uploads/images` and `public/uploads/photos` folders?

**Comment by yuri25** [comment]
The image folder was available, the photos folder was not ... I added, the images began to load, but the panel displays crookedly for some reason .....

**Comment by yuri25** [comment]
![image](https://user-images.githubusercontent.com/253228/66314469-bf56be80-e91c-11e9-8c49-ab69a76547f2.png)

**Comment by bpocallaghan** [comment]
Awesome, mmm, what is the source of the file? It might've happened that the photo were created (in database) but the file upload did not succeed. Maybe delete and try again.
Otherwise you can check what the 'path / source' of the image is - and then we take it from there :)

**Comment by yuri25** [comment]
Sorry ... This was my mistake due to the lack of a ssl-certificate. The problem is resolved.  Sorry again.

**Comment by bpocallaghan** [comment]
Hi @yuri25 
Awesome - glad its working :)
