### ISSUE TITLE
Error in running "php artisan titan:setup" command!!!

### ISSUE THREAD

**Issue by 34534206** [bpocallaghan/titan#31]
I got error as below, when i try to run php artisan titan:setup command. I did steps as you mentioned but don't know what went wrong. 
![error2](https://user-images.githubusercontent.com/66189342/87222331-932c0a80-c392-11ea-8dd6-a8a4c6ab833d.jpg)

**Comment by bpocallaghan** [comment]
Hi @34534206 
Thank you for trying out this project.
Sorry about the delay, I've published a fix for the error.

Please note this project is kinda deprecated and replaced with this one [Titan Starter](https://github.com/bpocallaghan/titan-starter) - Latest Adminlte Theme (bootstrap 4 and has some tests)

Please shout if you have more issues. Sorry and Thanks :)
